# Generated by Django 4.2.4 on 2023-08-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=80)),
                ('prod_price', models.IntegerField(default=0)),
                ('prod_decs', models.CharField(default='', max_length=200)),
                ('prod_img', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
