# Generated by Django 4.2.3 on 2023-08-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_prod_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_desc',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
