# Generated by Django 4.2.3 on 2023-08-08 09:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_customer_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_qty', models.IntegerField(default=1)),
                ('ord_price', models.IntegerField()),
                ('ord_addr', models.CharField(blank=True, default='', max_length=100)),
                ('ord_mob', models.CharField(blank=True, default='', max_length=10)),
                ('ord_date', models.DateField(default=datetime.datetime.today)),
                ('ord_cutm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
                ('ord_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
