# Generated by Django 4.2.3 on 2023-08-08 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='ord_addr',
            new_name='order_addr',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='ord_cutm',
            new_name='order_cutm',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='ord_date',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='ord_mob',
            new_name='order_mob',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='ord_price',
            new_name='order_price',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='ord_prod',
            new_name='order_prod',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='ord_qty',
            new_name='order_qty',
        ),
    ]
