# Generated by Django 4.2.3 on 2023-08-08 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_ord_addr_orders_order_addr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='order_addr',
            new_name='order_address',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='order_cutm',
            new_name='order_customer',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='order_mob',
            new_name='order_mobile',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='order_prod',
            new_name='order_product',
        ),
    ]
